"""empty message

Revision ID: 57505e1d1094
Revises: 7085f43fa8aa
Create Date: 2025-10-29 07:27:35.330577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57505e1d1094'
down_revision: Union[str, Sequence[str], None] = '7085f43fa8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profile_filters', ['id'])
    op.create_unique_constraint(None, 'profile_photos', ['id'])
    op.create_unique_constraint(None, 'profiles', ['id'])
    op.add_column('user_interactions', sa.Column('first_user_id', sa.UUID(), nullable=True))
    op.add_column('user_interactions', sa.Column('second_user_id', sa.UUID(), nullable=True))
    op.add_column('user_interactions', sa.Column('first_user_interaction_type', postgresql.ENUM('LIKE', 'DISLIKE', name='interaction_type_enum'), nullable=True))
    op.add_column('user_interactions', sa.Column('second_user_interaction_type', postgresql.ENUM('LIKE', 'DISLIKE', name='interaction_type_enum'), nullable=True))
    op.create_unique_constraint(None, 'user_interactions', ['id'])
    op.drop_constraint(op.f('user_interactions_from_user_id_fkey'), 'user_interactions', type_='foreignkey')
    op.drop_constraint(op.f('user_interactions_to_user_id_fkey'), 'user_interactions', type_='foreignkey')
    op.create_foreign_key(None, 'user_interactions', 'users', ['second_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_interactions', 'users', ['first_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_interactions', 'is_match')
    op.drop_column('user_interactions', 'from_user_id')
    op.drop_column('user_interactions', 'interaction_type')
    op.drop_column('user_interactions', 'to_user_id')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('user_interactions', sa.Column('to_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user_interactions', sa.Column('interaction_type', postgresql.ENUM('LIKE', 'DISLIKE', name='interaction_type_enum'), autoincrement=False, nullable=False))
    op.add_column('user_interactions', sa.Column('from_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user_interactions', sa.Column('is_match', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.create_foreign_key(op.f('user_interactions_to_user_id_fkey'), 'user_interactions', 'users', ['to_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_interactions_from_user_id_fkey'), 'user_interactions', 'users', ['from_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'user_interactions', type_='unique')
    op.drop_column('user_interactions', 'second_user_interaction_type')
    op.drop_column('user_interactions', 'first_user_interaction_type')
    op.drop_column('user_interactions', 'second_user_id')
    op.drop_column('user_interactions', 'first_user_id')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_constraint(None, 'profile_photos', type_='unique')
    op.drop_constraint(None, 'profile_filters', type_='unique')
    # ### end Alembic commands ###
